apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIGA/sOGGHcjcwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTYzOTk3NjU2NjAe
    Fw0yMTEyMjAwNTAyNDVaFw0yNDAyMTgwNTAyNDZaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE2Mzk5NzY1NjYwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMQobXFQWDNuFsbsszzrfyfM9Ml/NOrqL8
    vURvn76r1JPpjkpO6ltFS90VDThozrJs79ZBr3KwQtue+yy8ZPhs24wk6JR8vLJK
    VhM1e/CiCRAme9xyAdZamBe0eacffH6UEktSLK5LQfhhToBxkVkeMvc9UL/R6sV8
    bFvdXcgu6AI61ZGqzQq8RrdnOjXU7/yhSDvZkxB5jOxul3I+US+v7PW9cRH4ITtR
    Z3DowpbUiUj4w44VPhnI6iB44x0LSSP5AwR0ohhKuVz5SyJ9HBZ7j/w4Gerew4d8
    uG6YPZGJwOI2oQy91rcbGKsB/QfdCfag5ew97ZRY0BifE55b0V9BAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSf7zkr
    ciXE+R+6oa1pND+53lpNJzAfBgNVHSMEGDAWgBSf7zkrciXE+R+6oa1pND+53lpN
    JzANBgkqhkiG9w0BAQsFAAOCAQEAQBBKDHcEjBKirzr9d8UKKgG/cjo5K1W0JtyS
    UfYf0FVfYMScv2Wpo+k6SNiNJdl4UgFhz5fePC7F5N2YmdULIhHFxFEtkVEekQAy
    jH59yDpD12bxn1hDXKZR2bPPVSkbAZtgIfPWad2TbfTNrlAL4wv5dd1dQ8iNoIGF
    VRwUfAiEZPLTCIR1u1I/qIqUTwLS5SDMC2Y7x6jYrZe//1dgqq+Uj3y2tLf44Vpo
    av4ftYRd9SNZxV/2MGFgSMgvsxSSAIQRyAOyCenFV9hX4dlDrIipHTqnZDdCgC26
    M+EZ2+sfMZlZUQNTbaqiQElB146Muw4I1dMfGHV38b5R7aPZbw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-09T15:28:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:service-ca.crt: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"33272b4c-00ff-4713-a3fb-7ad657ae2430"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2022-01-09T15:28:46Z"
  name: blog-django-py-git-1-ca
  namespace: fiap-cgalvaojr
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: blog-django-py-git-1-build
    uid: 33272b4c-00ff-4713-a3fb-7ad657ae2430
  resourceVersion: "16251517"
  selfLink: /api/v1/namespaces/fiap-cgalvaojr/configmaps/blog-django-py-git-1-ca
  uid: 7ee06384-0772-4873-8b16-43c3a3c4c50f
---
apiVersion: v1
data:
  WebHookSecretKey: ZGZlY2UzNjM4MzhiNjk1Yg==
kind: Secret
metadata:
  creationTimestamp: "2022-01-09T15:28:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:WebHookSecretKey: {}
      f:type: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-09T15:28:45Z"
  name: blog-django-py-git-generic-webhook-secret
  namespace: fiap-cgalvaojr
  resourceVersion: "16251514"
  selfLink: /api/v1/namespaces/fiap-cgalvaojr/secrets/blog-django-py-git-generic-webhook-secret
  uid: d977f5a1-ff03-4715-9955-3ea6ee148db6
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
    volume.kubernetes.io/selected-node: na46-bjfsg-worker-0-25g6d
  creationTimestamp: "2022-01-09T15:42:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: sample-database
    app.kubernetes.io/component: sample-database
    app.kubernetes.io/instance: sample-database
    template: postgresql-persistent-template
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:template: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
    manager: oc
    operation: Update
    time: "2022-01-09T15:42:27Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:volume.kubernetes.io/selected-node: {}
    manager: kube-scheduler
    operation: Update
    time: "2022-01-09T15:42:32Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-09T15:42:33Z"
  name: sample-database
  namespace: fiap-cgalvaojr
  resourceVersion: "16259264"
  selfLink: /api/v1/namespaces/fiap-cgalvaojr/persistentvolumeclaims/sample-database
  uid: 70fdb0f6-86a2-484e-82ea-bf66d0b4ce28
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-70fdb0f6-86a2-484e-82ea-bf66d0b4ce28
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/openshift-katacoda/blog-django-py.git
    deployment.kubernetes.io/revision: "8"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"blog-django-py-git:latest","namespace":"fiap-cgalvaojr"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py-git\")].image","pause":"false"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"alpha.image.policy.openshift.io/resolve-names":"*","app.openshift.io/vcs-ref":"","app.openshift.io/vcs-uri":"https://github.com/openshift-katacoda/blog-django-py.git","deployment.kubernetes.io/revision":"8","image.openshift.io/triggers":"[{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"blog-django-py-git:latest\",\"namespace\":\"fiap-cgalvaojr\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"blog-django-py-git\\\")].image\",\"pause\":\"false\"}]","openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":"2022-01-09T15:28:46Z","generation":14,"labels":{"app":"blog-django-py-git","app.kubernetes.io/component":"blog-django-py-git","app.kubernetes.io/instance":"blog-django-py-git","app.kubernetes.io/name":"python","app.kubernetes.io/part-of":"blog-django-py-git-app","app.openshift.io/runtime":"python","app.openshift.io/runtime-version":"3.8-ubi7"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"blog-django-py-git\"}":{"f:image":{}}}}}}},"manager":"openshift-controller-manager","operation":"Update","time":"2022-01-09T15:29:56Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:alpha.image.policy.openshift.io/resolve-names":{},"f:app.openshift.io/vcs-ref":{},"f:app.openshift.io/vcs-uri":{},"f:image.openshift.io/triggers":{},"f:openshift.io/generated-by":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/component":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{},"f:app.openshift.io/runtime":{},"f:app.openshift.io/runtime-version":{}}},"f:spec":{"f:paused":{},"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:app":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{},"f:deploymentconfig":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"blog-django-py-git\"}":{".":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8080,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"Mozilla","operation":"Update","time":"2022-01-09T15:51:40Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-01-09T15:58:03Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"blog-django-py-git\"}":{"f:env":{".":{},"k:{\"name\":\"BLOG_BANNER_COLOR\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"BLOG_SITE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DATABASE_URL\"}":{".":{},"f:name":{},"f:value":{}}}}}}}}},"manager":"oc","operation":"Update","time":"2022-01-09T15:58:03Z"}],"name":"blog-django-py-git","namespace":"fiap-cgalvaojr","resourceVersion":"16270845","selfLink":"/apis/apps/v1/namespaces/fiap-cgalvaojr/deployments/blog-django-py-git","uid":"f2499613-8c36-41ef-a8aa-c017eec3ea26"},"spec":{"paused":true,"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"blog-django-py-git"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"blog-django-py-git","deploymentconfig":"blog-django-py-git"}},"spec":{"containers":[{"env":[{"name":"BLOG_BANNER_COLOR","value":"black"},{"name":"BLOG_SITE_NAME","value":"FIAP ASO CGALVAOJR"},{"name":"DATABASE_URL","value":"postgresql://sampledb:sampledb@sample-database:5432/sampledb"}],"image":"image-registry.openshift-image-registry.svc:5000/fiap-cgalvaojr/blog-django-py-git@sha256:d18c085741530d1078aca5dd54ede4c84734dddabcf08be4619e36edef1e448b","imagePullPolicy":"Always","name":"blog-django-py-git","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-01-09T15:38:18Z","lastUpdateTime":"2022-01-09T15:38:18Z","message":"Deployment is paused","reason":"DeploymentPaused","status":"Unknown","type":"Progressing"},{"lastTransitionTime":"2022-01-09T15:38:24Z","lastUpdateTime":"2022-01-09T15:38:24Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":14,"readyReplicas":1,"replicas":1}}
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2022-01-09T15:28:46Z"
  generation: 15
  labels:
    app: blog-django-py-git
    app.kubernetes.io/component: blog-django-py-git
    app.kubernetes.io/instance: blog-django-py-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-django-py-git-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"blog-django-py-git"}:
                f:image: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2022-01-09T15:29:56Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:alpha.image.policy.openshift.io/resolve-names: {}
          f:app.openshift.io/vcs-ref: {}
          f:app.openshift.io/vcs-uri: {}
          f:image.openshift.io/triggers: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.openshift.io/runtime: {}
          f:app.openshift.io/runtime-version: {}
      f:spec:
        f:paused: {}
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:deploymentconfig: {}
          f:spec:
            f:containers:
              k:{"name":"blog-django-py-git"}:
                .: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8080,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: Mozilla
    operation: Update
    time: "2022-01-09T15:51:40Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-09T15:58:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"blog-django-py-git"}:
                f:env:
                  .: {}
                  k:{"name":"BLOG_BANNER_COLOR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"BLOG_SITE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DATABASE_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: oc
    operation: Update
    time: "2022-01-09T15:58:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-01-20T23:18:27Z"
  name: blog-django-py-git
  namespace: fiap-cgalvaojr
  resourceVersion: "26509125"
  selfLink: /apis/apps/v1/namespaces/fiap-cgalvaojr/deployments/blog-django-py-git
  uid: f2499613-8c36-41ef-a8aa-c017eec3ea26
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blog-django-py-git
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-django-py-git
        deploymentconfig: blog-django-py-git
    spec:
      containers:
      - env:
        - name: BLOG_BANNER_COLOR
          value: black
        - name: BLOG_SITE_NAME
          value: FIAP ASO CGALVAOJR
        - name: DATABASE_URL
          value: postgresql://sampledb:sampledb@sample-database:5432/sampledb
        image: image-registry.openshift-image-registry.svc:5000/fiap-cgalvaojr/blog-django-py-git@sha256:d18c085741530d1078aca5dd54ede4c84734dddabcf08be4619e36edef1e448b
        imagePullPolicy: Always
        name: blog-django-py-git
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-09T15:38:18Z"
    lastUpdateTime: "2022-01-09T15:38:18Z"
    message: Deployment is paused
    reason: DeploymentPaused
    status: Unknown
    type: Progressing
  - lastTransitionTime: "2022-01-09T15:38:24Z"
    lastUpdateTime: "2022-01-09T15:38:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: criado-via-yaml
  namespace: fiap-cgalvaojr
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-django-py-git
