kind: ReplicaSet
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-django-py-git:latest","namespace":"fiap-aso-cgalvaojr"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-django-py-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/apps/v1/namespaces/fiap-aso-cgalvaojr/replicasets/blog-django-py-git-6bc488b9c5
  resourceVersion: '16254237'
  name: blog-django-py-git-6bc488b9c5
  uid: 0889e505-6c88-487b-8a1a-52504bdef6b3
  creationTimestamp: '2022-01-09T15:29:56Z'
  generation: 2
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-09T15:33:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:deployment.kubernetes.io/revision': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"f2499613-8c36-41ef-a8aa-c017eec3ea26"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
              'f:pod-template-hash': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"blog-django-py-git"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
        'f:status':
          'f:observedGeneration': {}
          'f:replicas': {}
  namespace: fiap-aso-cgalvaojr
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: blog-django-py-git
      uid: f2499613-8c36-41ef-a8aa-c017eec3ea26
      controller: true
      blockOwnerDeletion: true
  labels:
    app: blog-django-py-git
    deploymentconfig: blog-django-py-git
    pod-template-hash: 6bc488b9c5
spec:
  replicas: 0
  selector:
    matchLabels:
      app: blog-django-py-git
      pod-template-hash: 6bc488b9c5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-django-py-git
        deploymentconfig: blog-django-py-git
        pod-template-hash: 6bc488b9c5
    spec:
      containers:
        - name: blog-django-py-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/fiap-aso-cgalvaojr/blog-django-py-git@sha256:d18c085741530d1078aca5dd54ede4c84734dddabcf08be4619e36edef1e448b
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 0
  observedGeneration: 2
